version: '3.7'
services:
  api:
    image: api
    container_name: api
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - ${PORT:-3006}:${PORT:-3006}
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:1234@postgres:5432/menu}

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-1234}
      - POSTGRES_DB=menu
